[pytest]
testpaths = tests
pythonpath = .
asyncio_mode = strict
filterwarnings =
    ignore::DeprecationWarning
markers =
    integration: mark test as integration (requires Geth binary)
addopts = --strict-markers